<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- length width height -->
  <xacro:property name="chassis_length" value=".8" />
  <xacro:property name="chassis_width" value=".4" />
  <xacro:property name="chassis_height" value=".2" />

  <xacro:property name="chassis_size" value="${chassis_length} ${chassis_width} ${chassis_height}" />

  <xacro:property name="front_wheel_radius" value=".2" />
  <xacro:property name="front_wheel_thickness" value=".1" />
  <xacro:property name="front_wheel_x" value="${chassis_length/2 - front_wheel_radius}" />

  <xacro:property name="caster_radius" value="${front_wheel_radius - chassis_height/2}" />

  <xacro:macro name="caster_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
  </xacro:macro>

  <xacro:property name="camera_length" value=".05" />
  <xacro:property name="camera_width" value=".05" />
  <xacro:property name="camera_height" value=".05" />

  <xacro:macro name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
  </xacro:macro>

  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <box size="${chassis_size}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_size}"/>
      </geometry>
    </visual>
  </link>

  <link name="front_left_wheel">
    <inertial>
        <mass value="5"/>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <inertia
            ixx="0.1" ixy="0" ixz="0"
            iyy="0.1" iyz="0"
            izz="0.1"/>
    </inertial>

    <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
            <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
        </geometry>
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
            <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
        </geometry>
    </collision>
  </link>

  <link name="front_right_wheel">
    <inertial>
        <mass value="5"/>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <inertia
            ixx="0.1" ixy="0" ixz="0"
            iyy="0.1" iyz="0"
            izz="0.1"/>
    </inertial>

    <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
            <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
        </geometry>
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
            <cylinder radius="${front_wheel_radius}" length="${front_wheel_thickness}"/>
        </geometry>
    </collision>
  </link>

  <link name="caster">
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
        <inertia
            ixx="0.1" ixy="0" ixz="0"
            iyy="0.1" iyz="0"
            izz="0.1"/>
    </inertial>

    <visual name='caster_visual'>
      <xacro:caster_visual />
    </visual>

    <collision name='caster_collision'>
      <xacro:caster_visual />
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
  </link>

  <joint type="continuous" name="front_left_wheel_hinge">
    <origin xyz="${front_wheel_x} ${chassis_width/2 + front_wheel_thickness/2} 0" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="front_right_wheel_hinge">
    <origin xyz="${front_wheel_x} ${-(chassis_width/2 + front_wheel_thickness/2)} 0" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <joint type="fixed" name="caster_joint">
    <origin xyz="${-chassis_length/2 + caster_radius} 0 ${-chassis_height/2}" rpy="0 0 0"/>
    <child link="caster"/>
    <parent link="chassis"/>
  </joint>

  <link name="camera_link">
    <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
            ixx="1e-6" ixy="0" ixz="0"
            iyy="1e-6" iyz="0" izz="1e-6"/>
        <box_inertia
            m="0.1" x="0.05" y="0.05" z="0.05"/>
    </inertial>

    <visual>
        <xacro:camera_visual />
    </visual>

    <collision>
        <xacro:camera_visual />
    </collision>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${chassis_length/2 + camera_length/2} 0 ${-chassis_height/2 + camera_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera_link"/>
  </joint>

  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <link name="hokuyo">
    <inertial>
        <mass value="1e-5"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
            ixx="1e-6" ixy="0" ixz="0"
            iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
        </geometry>
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.1 0.1 0.1"/>
        </geometry>
    </collision>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>

  <gazebo reference="chassis">
      <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="front_left_wheel">
      <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="front_right_wheel">
      <material>Gazebo/Black</material>
  </gazebo>

</robot>
